# IMDb Srapping

In [4]:
import pandas as pd 
import requests
from bs4 import BeautifulSoup

In [5]:
url = 'https://www.imdb.com/search/title/?count=100&groups=top_1000&sort=user_rating'
response = requests.get(url)
soup = BeautifulSoup(response.content,'html.parser')

In [6]:
movie_name = []
year = []
time = []
rating = []
metascore = []
votes = []
gross = []

description = []
Director = []
Stars = []

In [7]:
#storing the meaningfull required data in the variable
movie_data = soup.findAll('div', attrs= {'class': 'lister-item mode-advanced'})

In [9]:
#calling one by one using for loop
for store in movie_data:
    name = store.h3.a.text
    movie_name.append(name)
    
    year_of_release = store.h3.find('span', class_ = 'lister-item-year text-muted unbold').text.replace('(', '').replace(')', '')
    year.append(year_of_release)
    
    runtime = store.p.find('span', class_ = 'runtime').text.replace(' min', '')
    time.append(runtime)
    
    rate = store.find('div', class_ = 'inline-block ratings-imdb-rating').text.replace('\n', '')
    rating.append(rate)
    
    meta  = store.find('span', class_ = 'metascore').text.replace(' ', '') if store.find('span', class_ = 'metascore') else '^^^^^^'
    metascore.append(meta)
    #since, gross and votes have same attributes, that's why we had created a common variable and then used indexing
    value = store.find_all('span', attrs = {'name': 'nv'})
    
    vote = value[0].text
    votes.append(vote)
    
    grosses = value[1].text if len(value) >1 else '*****'
    gross.append(grosses)
    
    # Description of the Movies
    describe = store.find_all('p', class_ = 'text-muted')
    description_ = describe[1].text.replace('\n', '') if len(describe) >1 else '*****'
    description.append(description_)
    
    #Cast Details -- Scraping Director name and Stars 
    cast = store.find("p", class_ = '')
    cast = cast.text.replace('\n', '').split('|')
    cast = [x.strip() for x in cast]
    cast = [cast[i].replace(j, "") for i,j in enumerate(["Director:", "Stars:"])]
    Director.append(cast[0])
    Stars.append([x.strip() for x in cast[1].split(",")])

In [12]:
#creating a dataframe using pandas library
movie_DF = pd.DataFrame({'Name of movie': movie_name, 'Year of relase': year, 'Watchtime': time, 'Movie Rating': rating, 'Metascore': metascore, 'Votes':votes ,'Gross collection':gross  ,'Description':description  ,'Director':Director,'Star':Stars})

In [13]:
#Saving data in Excel file:

movie_DF.to_excel("Top_100_IMDB_Movies.xlsx")

In [14]:
movie_DF

,Name of movie,Year of relase,Watchtime,Movie Rating,Metascore,Votes,Gross collection,Description,Director,Star
0,Jai Bhim,2021,164,9.5,^^^^^^,"142,015",*****,When a tribal man is arrested for a case of al...,T.J. Gnanavel,"[Suriya, Lijo Mol Jose, Manikandan, Rajisha Vi..."
1,The Shawshank Redemption,1994,142,9.3,80,"2,495,893",$28.34M,Two imprisoned men bond over a number of years...,Frank Darabont,"[Tim Robbins, Morgan Freeman, Bob Gunton, Will..."
2,The Godfather,1972,175,9.2,100,"1,721,252",$134.97M,The Godfather follows Vito Corleone Don of the...,Francis Ford Coppola,"[Marlon Brando, Al Pacino, James Caan, Diane K..."
3,Soorarai Pottru,2020,153,9.1,^^^^^^,"102,565",*****,"Nedumaaran Rajangam ""Maara"" sets out to make t...",Sudha Kongara,"[Suriya, Paresh Rawal, Aparna Balamurali, Supe..."
4,The Dark Knight,2008,152,9.0,84,"2,446,825",$534.86M,When the menace known as the Joker wreaks havo...,Christopher Nolan,"[Christian Bale, Heath Ledger, Aaron Eckhart, ..."
...,...,...,...,...,...,...,...,...,...,...
195,Drishyam,2013,160,8.3,^^^^^^,"38,599",*****,A man goes to extreme lengths to save his fami...,Jeethu Joseph,"[Mohanlal, Meena, Asha Sharath, Ansiba]"
196,Jagten,2012,115,8.3,77,"307,534",$0.69M,"A teacher lives a lonely life, all the while s...",Thomas Vinterberg,"[Mads Mikkelsen, Thomas Bo Larsen, Annika Wedd..."
197,Jodaeiye Nader az Simin,2011,123,8.3,95,"233,852",$7.10M,A married couple are faced with a difficult de...,Asghar Farhadi,"[Payman Maadi, Leila Hatami, Sareh Bayat, Shah..."
198,Incendies,2010,131,8.3,80,"165,309",$6.86M,Twins journey to the Middle East to discover t...,Denis Villeneuve,"[Lubna Azabal, Mélissa Désormeaux-Poulin, Maxi..."
199,The Father,I 2020,97,8.3,88,"107,559",*****,A man refuses all assistance from his daughter...,Florian Zeller,"[Anthony Hopkins, Olivia Colman, Mark Gatiss, ..."